global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bifrost-server'
    static_configs:
      - targets: ['bifrost-server:9090']

  - job_name: 'bifrost-client'
    static_configs:
      - targets: ['bifrost-client:3129']
